import { Inter } from "next/font/google";
import "./globals.css";
import Menubar from "@/Components/Menubar/Menubar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Biz Master",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menubar />
        {children}
      </body>
    </html>
  );
}
